version: '3'
services:
  web:
    image: nginx:stable
    volumes:
      - ./config/load-balancer.conf:/etc/nginx/conf.d/load-balancer.conf ro
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_PORT=80
    networks:
      - elk

networks:
  elk:
    driver: bridge
